// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace CSharpPerformancePlaybook.EFCore
{
    // SalesTerritoryHistory
    /// <summary>
    /// Sales representative transfers to other sales territories.
    /// </summary>
    public class Sales_SalesTerritoryHistory
    {
        /// <summary>
        /// Primary key. The sales rep.  Foreign key to SalesPerson.BusinessEntityID.
        /// </summary>
        public int BusinessEntityId { get; set; } // BusinessEntityID (Primary key)

        /// <summary>
        /// Primary key. Territory identification number. Foreign key to SalesTerritory.SalesTerritoryID.
        /// </summary>
        public int TerritoryId { get; set; } // TerritoryID (Primary key)

        /// <summary>
        /// Primary key. Date the sales representive started work in the territory.
        /// </summary>
        public DateTime StartDate { get; set; } // StartDate (Primary key)

        /// <summary>
        /// Date the sales representative left work in the territory.
        /// </summary>
        public DateTime? EndDate { get; set; } // EndDate

        /// <summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        /// </summary>
        public Guid Rowguid { get; set; } // rowguid

        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        public DateTime ModifiedDate { get; set; } // ModifiedDate

        // Foreign keys

        /// <summary>
        /// Parent Sales_SalesPerson pointed by [SalesTerritoryHistory].([BusinessEntityId]) (FK_SalesTerritoryHistory_SalesPerson_BusinessEntityID)
        /// </summary>
        public virtual Sales_SalesPerson Sales_SalesPerson { get; set; } // FK_SalesTerritoryHistory_SalesPerson_BusinessEntityID

        /// <summary>
        /// Parent Sales_SalesTerritory pointed by [SalesTerritoryHistory].([TerritoryId]) (FK_SalesTerritoryHistory_SalesTerritory_TerritoryID)
        /// </summary>
        public virtual Sales_SalesTerritory Sales_SalesTerritory { get; set; } // FK_SalesTerritoryHistory_SalesTerritory_TerritoryID

        public Sales_SalesTerritoryHistory()
        {
            Rowguid = Guid.NewGuid();
            ModifiedDate = DateTime.Now;
        }
    }

}
// </auto-generated>
