// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace CSharpPerformancePlaybook.EFCore
{
    // SalesReason
    /// <summary>
    /// Lookup table of customer purchase reasons.
    /// </summary>
    public class Sales_SalesReason
    {
        /// <summary>
        /// Primary key for SalesReason records.
        /// </summary>
        public int SalesReasonId { get; set; } // SalesReasonID (Primary key)

        /// <summary>
        /// Sales reason description.
        /// </summary>
        public string Name { get; set; } // Name (length: 50)

        /// <summary>
        /// Category the sales reason belongs to.
        /// </summary>
        public string ReasonType { get; set; } // ReasonType (length: 50)

        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        public DateTime ModifiedDate { get; set; } // ModifiedDate

        public Sales_SalesReason()
        {
            ModifiedDate = DateTime.Now;
        }
    }

}
// </auto-generated>
