// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace CSharpPerformancePlaybook.EFCore
{
    // SalesTaxRate
    /// <summary>
    /// Tax rate lookup table.
    /// </summary>
    public class Sales_SalesTaxRate
    {
        /// <summary>
        /// Primary key for SalesTaxRate records.
        /// </summary>
        public int SalesTaxRateId { get; set; } // SalesTaxRateID (Primary key)

        /// <summary>
        /// State, province, or country/region the sales tax applies to.
        /// </summary>
        public int StateProvinceId { get; set; } // StateProvinceID

        /// <summary>
        /// 1 = Tax applied to retail transactions, 2 = Tax applied to wholesale transactions, 3 = Tax applied to all sales (retail and wholesale) transactions.
        /// </summary>
        public byte TaxType { get; set; } // TaxType

        /// <summary>
        /// Tax rate amount.
        /// </summary>
        public decimal TaxRate { get; set; } // TaxRate

        /// <summary>
        /// Tax rate description.
        /// </summary>
        public string Name { get; set; } // Name (length: 50)

        /// <summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        /// </summary>
        public Guid Rowguid { get; set; } // rowguid

        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        public DateTime ModifiedDate { get; set; } // ModifiedDate

        public Sales_SalesTaxRate()
        {
            TaxRate = 0.00m;
            Rowguid = Guid.NewGuid();
            ModifiedDate = DateTime.Now;
        }
    }

}
// </auto-generated>
