// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace CSharpPerformancePlaybook.EFCore
{
    // SpecialOffer
    /// <summary>
    /// Sale discounts lookup table.
    /// </summary>
    public class Sales_SpecialOffer
    {
        /// <summary>
        /// Primary key for SpecialOffer records.
        /// </summary>
        public int SpecialOfferId { get; set; } // SpecialOfferID (Primary key)

        /// <summary>
        /// Discount description.
        /// </summary>
        public string Description { get; set; } // Description (length: 255)

        /// <summary>
        /// Discount precentage.
        /// </summary>
        public decimal DiscountPct { get; set; } // DiscountPct

        /// <summary>
        /// Discount type category.
        /// </summary>
        public string Type { get; set; } // Type (length: 50)

        /// <summary>
        /// Group the discount applies to such as Reseller or Customer.
        /// </summary>
        public string Category { get; set; } // Category (length: 50)

        /// <summary>
        /// Discount start date.
        /// </summary>
        public DateTime StartDate { get; set; } // StartDate

        /// <summary>
        /// Discount end date.
        /// </summary>
        public DateTime EndDate { get; set; } // EndDate

        /// <summary>
        /// Minimum discount percent allowed.
        /// </summary>
        public int MinQty { get; set; } // MinQty

        /// <summary>
        /// Maximum discount percent allowed.
        /// </summary>
        public int? MaxQty { get; set; } // MaxQty

        /// <summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        /// </summary>
        public Guid Rowguid { get; set; } // rowguid

        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        public DateTime ModifiedDate { get; set; } // ModifiedDate

        // Reverse navigation

        /// <summary>
        /// Child Sales_SpecialOfferProducts where [SpecialOfferProduct].[SpecialOfferID] point to this entity (FK_SpecialOfferProduct_SpecialOffer_SpecialOfferID)
        /// </summary>
        public virtual ICollection<Sales_SpecialOfferProduct> Sales_SpecialOfferProducts { get; set; } // SpecialOfferProduct.FK_SpecialOfferProduct_SpecialOffer_SpecialOfferID

        public Sales_SpecialOffer()
        {
            DiscountPct = 0.00m;
            MinQty = 0;
            Rowguid = Guid.NewGuid();
            ModifiedDate = DateTime.Now;
            Sales_SpecialOfferProducts = new List<Sales_SpecialOfferProduct>();
        }
    }

}
// </auto-generated>
