// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CSharpPerformancePlaybook.EFCore
{
    // SalesReason
    public class Sales_SalesReasonConfiguration : IEntityTypeConfiguration<Sales_SalesReason>
    {
        public void Configure(EntityTypeBuilder<Sales_SalesReason> builder)
        {
            builder.ToTable("SalesReason", "Sales");
            builder.HasKey(x => x.SalesReasonId).HasName("PK_SalesReason_SalesReasonID").IsClustered();

            builder.Property(x => x.SalesReasonId).HasColumnName(@"SalesReasonID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.ReasonType).HasColumnName(@"ReasonType").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
        }
    }

}
// </auto-generated>
