// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CSharpPerformancePlaybook.EFCore
{
    // SpecialOffer
    public class Sales_SpecialOfferConfiguration : IEntityTypeConfiguration<Sales_SpecialOffer>
    {
        public void Configure(EntityTypeBuilder<Sales_SpecialOffer> builder)
        {
            builder.ToTable("SpecialOffer", "Sales");
            builder.HasKey(x => x.SpecialOfferId).HasName("PK_SpecialOffer_SpecialOfferID").IsClustered();

            builder.Property(x => x.SpecialOfferId).HasColumnName(@"SpecialOfferID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar(255)").IsRequired().HasMaxLength(255);
            builder.Property(x => x.DiscountPct).HasColumnName(@"DiscountPct").HasColumnType("smallmoney").IsRequired();
            builder.Property(x => x.Type).HasColumnName(@"Type").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.Category).HasColumnName(@"Category").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.StartDate).HasColumnName(@"StartDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.EndDate).HasColumnName(@"EndDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.MinQty).HasColumnName(@"MinQty").HasColumnType("int").IsRequired();
            builder.Property(x => x.MaxQty).HasColumnName(@"MaxQty").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Rowguid).HasColumnName(@"rowguid").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            builder.HasIndex(x => x.Rowguid).HasDatabaseName("AK_SpecialOffer_rowguid").IsUnique();
        }
    }

}
// </auto-generated>
